### ISSUE TITLE
How to generate training and testing data?

### ISSUE THREAD

**Issue by ynandwan** [ryanzhangfan/NeuroSAT#2]
Hi
Is it possible for you to share a shell script that runs data_maker.py and generates the train, val and test data for replicate the results?

Thanks!

**Comment by ryanzhangfan** [comment]
Generally, you can run the following script to generate 30,000 problems which variable number varies in [40, 40] used for validate or test. 12000 means the maximum number of nodes in one batch is 12000. --one denotes that allows only one problem in a batch. 

`python src/data_maker.py \`
       `'data/val/val_nv_40_npb_12000.pkl' \`
       `'log/neurosat_3sat_sr200_gen.log' \`
       `30000 \`
       `12000 \`
       `--min_n 40 \`
       `--max_n 40 \`
       `--one`

Since the author claims that they use a few millions of problems to train on SR(10, 40)[wiki](https://github.com/dselsam/neurosat/wiki/On-reproducing-the-experiments). Due to the disk space issue, we choose to generate the training problems online during training. So you don't need to generate training data additionally. In our training scripts, e.g. `run_sr10to40.sh`, there are also two arguments "--min_n" and "--max_n" to specify the min variable number and max variable number of generated training problems.

But if you do want to do so, you can also use script above by changing the "--min_n" to 10 and '30000' term to the problems number you want. And of course, removing the "--one" line.

**Comment by ynandwan** [comment]
Thanks for such a prompt response! If we are using --one flag, which allows only one problem in a batch,  then what does it mean to have 12000  numbers of nodes in one batch? I am sure one problem would not have 12000 nodes.

**Comment by ryanzhangfan** [comment]
12000 term means the possible maximum node number in one batch. This param is usually used to prevent running out of gpu memory during training or testing. If “—one” is enabled and the node number of given problem is less than 12000, then the problem will be successfully packaged in this batch, and the node number of this batch is the node number of this problem. If a problem has more than 12000 nodes, it will be discarded during the generation phase. 

Besides, this param is more useful in training data generation process(“—one” is disabled). Since the node number of one problem is often much less than 12000, and to accelerate the training, we often package more than one problems into one batch, and the 12000 term is used to limit the batch size. It guarantees that the total nodes number of problems in one batch is less or equal than 12000.

P.s. Enabling “—one” is more friendly for us human to check data and results one by one. In fact, it’s also ok not to enable this flag when generating val or test data, since there is no difference for the codes to process one problem in a batch or multiple problems in a batch.

**Comment by ynandwan** [comment]
Got it, Thanks!
